"""
Django settings for bookstore project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url  # Importe dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use uma variável de ambiente para a SECRET_KEY em produção
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-f*k@=53bc5!shef1-6w+m$-g)kspbaljz%8k4(j7iuc-u2_dyd"
)
# A chave padrão (django-insecure-...) será usada apenas se SECRET_KEY não for definida no ambiente.
# No Render, você definirá SECRET_KEY como uma variável de ambiente forte.

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG deve ser False em produção. Use 0 ou 1 do ambiente para controle.
DEBUG = int(os.environ.get("DEBUG", 0))  # Converte para int para garantir False/True

# ALLOWED_HOSTS para o Render e desenvolvimento local
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(" ")
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "order",
    "product",
    "rest_framework",
    "rest_framework.authtoken",
]

# Adicione django-debug-toolbar apenas se DEBUG for True
if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Adicione Whitenoise para servir arquivos estáticos em produção ANTES do CommonMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Adicione esta linha
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Adicione debug_toolbar.middleware.DebugToolbarMiddleware apenas se DEBUG for True
if DEBUG:
    MIDDLEWARE.insert(
        0, "debug_toolbar.middleware.DebugToolbarMiddleware"
    )  # Inserir no início da lista

ROOT_URLCONF = "bookstore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bookstore.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Configuração de banco de dados para desenvolvimento local (se DATABASE_URL não estiver definida)
# e para produção (usando DATABASE_URL do Render)
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,  # Tempo de vida máximo das conexões (em segundos)
            conn_health_checks=True,  # Habilita health checks de conexão
        )
    }
else:
    # Configuração de banco de dados para desenvolvimento local (do seu env.dev)
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
            "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
            "USER": os.environ.get("SQL_USER", ""),
            "PASSWORD": os.environ.get("SQL_PASSWORD", ""),
            "HOST": os.environ.get("SQL_HOST", ""),
            "PORT": os.environ.get("SQL_PORT", ""),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
# Onde `collectstatic` vai copiar os arquivos estáticos para produção
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use Whitenoise para servir arquivos estáticos em produção
# Isso é crucial para o Render quando não se usa um serviço de Static Site dedicado.
# Ele deve ser usado APENAS em produção (quando DEBUG é False)
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 5,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# INTERNAL_IPS para django-debug-toolbar
# Ativo apenas se DEBUG for True
if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
        # Adicione o IP do seu ambiente de desenvolvimento se precisar acessar o debug toolbar de outra máquina
        # ou o Render pode injetar o IP do cliente.
    ]

# Configuração adicional para o django-extensions (opcional, apenas para desenvolvimento)
SHELL_PLUS = "ipython"  # ou 'bpython'
